In [ ]:
import numpy as np

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
n=np.arange(1,11)
print (n)

[ 1  2  3  4  5  6  7  8  9 10]


no arithm opetn

In [ ]:
n=np.arange(3)
n+n

array([0, 2, 4])

In [ ]:
c=n*n
c

array([0, 1, 4])

In [ ]:
b=n-n
b

array([0, 0, 0])

In [ ]:
a=n/n
print (a)

[nan  1.  1.]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
n1=np.arange(1,3)
a1=n1/n1
a1

array([1., 1.])

In [ ]:
o=n+n
o

array([0, 2, 4])

In [ ]:
import numpy as npp
npp.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
npp.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
npp.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])